"""Phrase -> booru tag mapping used by the import/draft tooling.

Two jobs:

1. ``tags_for_text`` derives booru tags for an existing catalog entry from its
   name / natural-language clause. Rules are ordered keyword -> tags pairs.
2. ``normalise_tags`` cleans a raw tag list (e.g. the tag column of the idea
   tables, which contains a lot of snake-cased English that is not a real tag)
   against ``data/danbooru_tags.txt``, applying aliases and dropping the rest.

Nothing here touches the runtime; the node only ever reads the built JSON.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VOCAB_PATH = os.path.join(ROOT, "data", "tags.txt")


def load_vocab():
    vocab = set()
    with open(VOCAB_PATH, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            vocab.add(line)
    return vocab


VOCAB = load_vocab()

# Invented / non-existent tags -> real vocabulary. Anything not resolvable is
# dropped by ``normalise_tags`` and reported by the linter.
ALIASES = {
    "3d_render": "3d",
    "octane_render": "3d",
    "cycles_render": "3d",
    "cycles": "3d",
    "redshift": "3d",
    "vray": "3d",
    "unreal_engine_cinematic": "3d",
    "path_traced": "3d",
    "pbr_materials": "3d",
    "hard-surface_modeling": "3d",
    "clay_render": "claymation",
    "photogrammetry_look": "3d",
    "isometric_3d": "3d",
    "cel-shaded_3d": "cel_shading",
    "painterly_3d": "painting_(medium)",
    "voxel": "pixel_art",
    "low-poly": "low_poly",
    "wireframe_overlay": "wireframe",
    "realtime": "3d",
    "subsurface_scattering": "realistic",
    "glitch_art": "glitch",
    "hologram": "holographic",
    "oil_on_canvas": "oil_painting_(medium)",
    "baroque_oil": "oil_painting_(medium)",
    "impasto": "oil_painting_(medium)",
    "glazing": "oil_painting_(medium)",
    "watercolor": "watercolor_(medium)",
    "wet-on-wet": "watercolor_(medium)",
    "gouache": "gouache_(medium)",
    "tempera": "tempera_(medium)",
    "fresco": "painting_(medium)",
    "acrylic": "acrylic_paint_(medium)",
    "sumi-e": "ink_wash_painting",
    "gongbi": "ink_wash_painting",
    "xieyi": "ink_wash_painting",
    "charcoal": "charcoal_(medium)",
    "graphite_study": "graphite_(medium)",
    "colored_pencil": "colored_pencil_(medium)",
    "pastel": "pastel_(medium)",
    "ballpoint_sketch": "ballpoint_pen_(medium)",
    "stipple": "halftone",
    "etching": "lithograph",
    "engraving": "lithograph",
    "linocut": "woodcut",
    "screenprint": "stencil",
    "letterpress": "traditional_media",
    "comic_ink": "comic",
    "spot_black": "high_contrast",
    "marker_rendering": "marker_(medium)",
    "matte_painting": "concept_art",
    "digital_painting": "painting_(medium)",
    "photobash_concept": "concept_art",
    "speedpaint": "sketch",
    "photocopy": "monochrome",
    "photogravure": "sepia",
    "cyanotype": "blue_theme",
    "35mm_film": "photo_(medium)",
    "medium_format": "photo_(medium)",
    "large_format": "photo_(medium)",
    "view_camera_4x5": "photo_(medium)",
    "8x10": "photo_(medium)",
    "6x6_hasselblad-like": "photo_(medium)",
    "rangefinder_street_kit": "photo_(medium)",
    "twin-lens_rollei_look": "photo_(medium)",
    "polaroid": "instant_photo",
    "instant": "instant_photo",
    "kodak_portra_400": "photo_(medium)",
    "kodak_gold_200": "photo_(medium)",
    "cinestill_800t": "photo_(medium)",
    "fuji_pro_400h": "photo_(medium)",
    "ilford_hp5": "monochrome",
    "tri-x_400": "monochrome",
    "daguerreotype": "sepia",
    "wet_plate_collodion": "sepia",
    "tintype": "sepia",
    "albumen_print": "sepia",
    "lith_print": "monochrome",
    "selenium_tone": "monochrome",
    "platinum": "monochrome",
    "palladium": "monochrome",
    "split_tone": "duotone",
    "toy_camera": "photo_(medium)",
    "holga": "photo_(medium)",
    "expired_film": "photo_(medium)",
    "cross-processed": "photo_(medium)",
    "film_grain_subtle": "film_grain",
    "halation_subtle": "lens_flare",
    "crt": "glitch",
    "vhs": "glitch",
    "early_digital_video": "glitch",
    "arri_alexa_look": "cinematic_lighting",
    "anamorphic_still": "lens_flare",
    "pinhole": "photo_(medium)",
    "infrared": "photo_(medium)",
    "multiple_exposure": "photo_(medium)",
    "push-processed_film": "film_grain",
    "photorealism_as_painting": "photorealistic",
    "raw_photo": "photo_(medium)",
    "shot_on_film": "film_grain",
    "natural_skin_texture": "realistic",
    "visible_pores": "realistic",
    "catchlights": "realistic",
    "imperfections": "realistic",
    "detailed_skin": "realistic",
    "hyperrealistic": "photorealistic",
    "lifelike": "realistic",
    "documentary_photography": "photo_(medium)",
    "photojournalism": "photo_(medium)",
    "editorial_photography": "photo_(medium)",
    "fine-art_photography": "photo_(medium)",
    "snapshot": "photo_(medium)",
    "candid": "photo_(medium)",
    "street_photography": "photo_(medium)",
    "street": "photo_(medium)",
    "headshot": "portrait",
    "environmental_portrait": "portrait",
    "fashion_editorial": "photo_(medium)",
    "beauty_photography": "portrait",
    "boudoir": "photo_(medium)",
    "fine-art_nude": "photo_(medium)",
    "glamour": "photo_(medium)",
    "pin-up": "photo_(medium)",
    "product_packshot": "simple_background",
    "product": "simple_background",
    "food_photography": "photo_(medium)",
    "still_life": "still_life",
    "architecture_photography": "scenery",
    "interior_dusk_lamps-on": "scenery",
    "landscape": "scenery",
    "seascape": "scenery",
    "wildlife": "photo_(medium)",
    "bird-in-flight": "motion_blur",
    "macro": "depth_of_field",
    "sports_peak_action": "motion_blur",
    "dance_still": "motion_blur",
    "concert": "backlighting",
    "wedding_reportage": "photo_(medium)",
    "automotive": "photo_(medium)",
    "aviation": "scenery",
    "maritime_work_deck": "scenery",
    "astro": "scenery",
    "nightscape": "scenery",
    "light_painting": "long_exposure",
    "aerial": "scenery",
    "drone": "scenery",
    "surveillance-cam": "fake_screenshot",
    "paparazzi_tele": "photo_(medium)",
    "id": "photo_(medium)",
    "passport_light": "photo_(medium)",
    "family-album_flash": "flash_photography",
    "camera-phone_candid": "photo_(medium)",
    "cinematic": "cinematic_lighting",
    "worn": "textured",
    "character_sheet": "character_sheet",
    "model_sheet": "reference_sheet",
    "turnaround_front_side_back": "turnaround",
    "expression_sheet": "multiple_views",
    "pose_sheet": "multiple_views",
    "detail_callout_sheet": "reference_sheet",
    "splash_art": "official_art",
    "app_icon": "icon_(computing)",
    "icon": "icon_(computing)",
    "avatar_bust": "portrait",
    "wallpaper_desktop": "wallpaper",
    "phone_wallpaper": "wallpaper",
    "thumbnail": "poster",
    "album_cover_square": "album_cover",
    "book_jacket": "cover",
    "tarot_card": "trading_card",
    "trading_card_bust": "trading_card",
    "poster_one-sheet": "poster",
    "playbill": "poster",
    "magazine_cover": "magazine_cover",
    "editorial_double-page": "magazine_cover",
    "lookbook_row": "multiple_views",
    "packshot": "simple_background",
    "lifestyle_product_still": "photo_(medium)",
    "storyboard_panel": "storyboard",
    "page": "comic",
    "webtoon_vertical_slice": "webtoon",
    "cinematic_still_2391": "widescreen",
    "polaroid_frame": "instant_photo",
    "contact_sheet": "contact_sheet",
    "triptych": "multiple_views",
    "diptych_before": "multiple_views",
    "after": "multiple_views",
    "infographic_still": "diagram",
    "ui_mock_screenshot": "fake_screenshot",
    "interface": "fake_screenshot",
    "map_as_picture": "map",
    "blueprint": "diagram",
    "orthographic_tech_drawing": "diagram",
    "exploded_view": "diagram",
    "cutaway": "diagram",
    "character_select": "multiple_views",
    "reference_sheet": "reference_sheet",
    "sheet": "multiple_views",
    "item": "simple_background",
    "compass_rose": "map",
    "grid": "diagram",
    "classical_antiquity": "greyscale",
    "hellenistic": "greyscale",
    "byzantine_gold_ground": "gold",
    "medieval_illumination": "gold",
    "gothic_elongation": "stained_glass",
    "early": "painting_(medium)",
    "high_renaissance": "painting_(medium)",
    "northern_renaissance": "oil_painting_(medium)",
    "mannerism": "painting_(medium)",
    "baroque": "chiaroscuro",
    "caravaggesque": "chiaroscuro",
    "rococo": "pastel_colors",
    "neoclassical": "painting_(medium)",
    "romanticism": "painting_(medium)",
    "hudson_river_school": "scenery",
    "realism_courbet-line": "painting_(medium)",
    "pre-raphaelite": "painting_(medium)",
    "post-impressionism": "impressionism",
    "pointillism": "halftone",
    "symbolism": "surreal",
    "vienna_secession": "art_nouveau",
    "tonalism": "muted_color",
    "fauvism": "colorful",
    "german_expressionism": "woodcut",
    "cubism": "cubism",
    "futurism": "motion_lines",
    "constructivism": "poster",
    "de_stijl": "minimalism",
    "bauhaus": "minimalism",
    "streamline_moderne": "art_deco",
    "surrealism": "surreal",
    "dada_collage": "collage",
    "abstract_expressionism": "painting_(medium)",
    "color_field": "gradient",
    "pop_art": "halftone",
    "op_art": "psychedelic",
    "street_muralism": "scenery",
    "lowbrow": "surreal",
    "pop_surreal": "surreal",
    "afrofuturist_art": "surreal",
    "contemporary_figurative": "painting_(medium)",
    "shin-hanga": "ukiyo-e",
    "persian_miniature": "gold",
    "mughal_miniature": "gold",
    "thangka": "gold",
    "mexican_muralism": "scenery",
    "soviet_poster": "poster",
    "wpa_poster": "poster",
    "swiss_international": "minimalism",
    "polish_school_of_posters": "poster",
    "psychedelic_poster": "psychedelic",
    "tattoo_flash_sheet": "multiple_views",
    "botanical_illustration": "diagram",
    "scientific_illustration": "diagram",
    "bestiary_page": "diagram",
    "kawaii_rounded_safe_decorated": "chibi",
    "super-deformed_24_heads": "super_deformed",
    "plush_visible_stitch": "textured",
    "felted_wool_handmade": "textured",
    "amigurumi_crochet_logic": "knitted",
    "yuru-chara_readable_silhouette": "chibi",
    "mascot": "chibi",
    "pastel_peach-cream_strawberry-milk_mint-lilac": "pastel_colors",
    "cel_shading_hard_shadow_bands": "cel_shading",
    "two-tone_vs_three-band_light": "cel_shading",
    "clean_lineart_variable_weight": "lineart",
    "thin_shōjo_line": "shoujo",
    "screentone_manga_dots": "screentones",
    "speed_lines_impact_still": "speed_lines",
    "painterly_key_visual_not_tv_cel": "key_visual",
    "ghibli-adjacent_watercolor_background": "watercolor_(medium)",
    "1990s_ova_grain_analog_airbrush": "1990s_(style)",
    "1970s_tv_simple_warm_limited": "1970s_(style)",
    "webgen": "highres",
    "pixiv_digital_polish": "highres",
    "manhwa_long-scroll_polish": "manhwa",
    "huge_reflective_irises_emotion_mirrors": "sparkle",
    "shining_eyes": "sparkle",
    "power_aura_hair_physics": "emphasis_lines",
    "blush": "blush_stickers",
    "anime_illustration": "anime_coloring",
    "thick_outlines": "outline",
    "no_lineart": "no_lineart",
    "painterly": "painting_(medium)",
    "watercolor_anime": "watercolor_(medium)",
    "oekaki": "oekaki",
    "gacha_key": "official_art",
    "utsushi": "photorealistic",
    "kemono": "kemonomimi",
    "furry": "kemonomimi",
    "shounen": "shounen",
    "shoujo": "shoujo",
    "moe": "moe",
    "vaporwave": "vaporwave",
    "synthwave": "neon_palette",
    "outrun": "neon_palette",
    "y2k": "holographic",
    "mcbling": "shiny",
    "frutiger_aero": "glass",
    "webcore": "glitch",
    "weirdcore": "surreal",
    "dreamcore": "surreal",
    "liminal_space": "scenery",
    "backrooms_yellow": "yellow_theme",
    "analog_horror": "analog_horror",
    "old_hollywood_glamour": "monochrome",
    "hollywood_regency": "scenery",
    "japandi": "minimalism",
    "wabi-sabi": "muted_color",
    "mid-century_modern": "scenery",
    "memphis_milano": "colorful",
    "brutalism": "stone",
    "maximalism": "colorful",
    "minimalism_lifestyle": "minimalism",
    "industrial_loft": "scenery",
    "night_luxe": "neon_palette",
    "la_dolce_vita": "scenery",
    "tropical_modernism": "scenery",
    "noir": "chiaroscuro",
    "neo-noir": "neon_palette",
    "cyberpunk": "neon_palette",
    "steampunk": "brown_theme",
    "dieselpunk": "brown_theme",
    "atompunk": "retro_artstyle",
    "raygun_gothic": "retro_artstyle",
    "retrofuturism": "retro_artstyle",
    "solarpunk": "green_theme",
    "lunarpunk": "glowing",
    "biopunk": "green_theme",
    "ink_wash": "ink_wash_painting",
    "ahoge_hair_antenna": "ahoge",
    "tiny_hat_on_an_animal": "ahoge",
    "school_rooftop": "rooftop",
    "konbini_night": "convenience_store",
    "vending_glow": "vending_machine",
    "trad_goth": "goth_fashion",
    "mall_goth": "goth_fashion",
    "nu-goth": "goth_fashion",
}

# Ordered keyword -> tags rules used to derive tags from an entry's name +
# natural-language clause. First match wins per tag; several rules may fire.
RULES = [
    (r"\banime\b|\bcel\b|\bOVA\b|\bshoujo\b|\bshounen\b|\bshonen\b", ["anime_coloring"]),
    (r"\bcel[- ]shad", ["cel_shading"]),
    (r"\bmanga\b|\bscreentone", ["manga", "screentones"]),
    (r"\b4[- ]?koma\b", ["4koma"]),
    (r"\bwebtoon\b|\bmanhwa\b", ["webtoon", "manhwa"]),
    (r"\bchibi\b|\bsuper[- ]deformed\b", ["chibi", "super_deformed"]),
    (r"\bgekiga\b", ["gekiga"]),
    (r"\bseinen\b", ["seinen"]),
    (r"\bjosei\b", ["josei"]),
    (r"\bmoe\b", ["moe"]),
    (r"\bbishoujo\b|\bbishojo\b", ["bishoujo"]),
    (r"\bkey visual\b", ["key_visual"]),
    (r"\bofficial art\b|\bgacha\b|\bsplash art\b", ["official_art"]),
    (r"1960s|1970s|\b70s\b", ["1970s_(style)", "retro_artstyle"]),
    (r"1980s|\b80s\b", ["1980s_(style)", "retro_artstyle"]),
    (r"1990s|\b90s\b", ["1990s_(style)"]),
    (r"2000s", ["2000s_(style)"]),
    (r"2010s", ["2010s_(style)"]),
    (r"\boil\b|\bimpasto\b|\bglazing\b", ["oil_painting_(medium)", "traditional_media"]),
    (r"\bwatercolou?r\b", ["watercolor_(medium)", "traditional_media"]),
    (r"\bgouache\b", ["gouache_(medium)", "traditional_media"]),
    (r"\btempera\b", ["tempera_(medium)", "traditional_media"]),
    (r"\bacrylic\b", ["acrylic_paint_(medium)", "traditional_media"]),
    (r"\bink wash\b|\bsumi-?e\b", ["ink_wash_painting", "traditional_media"]),
    (r"\bcharcoal\b", ["charcoal_(medium)", "traditional_media"]),
    (r"\bgraphite\b|\bpencil sketch\b", ["graphite_(medium)", "sketch"]),
    (r"\bcolou?red pencil\b", ["colored_pencil_(medium)"]),
    (r"\bpastel\b", ["pastel_(medium)"]),
    (r"\bballpoint\b", ["ballpoint_pen_(medium)"]),
    (r"\bmarker\b|\bcopic\b", ["marker_(medium)"]),
    (r"\bcross-?hatch", ["cross-hatching"]),
    (r"\bstipple\b|\bben-?day\b|\bhalftone\b", ["halftone"]),
    (r"\bwoodcut\b|\blinocut\b|\bwoodblock\b", ["woodcut", "traditional_media"]),
    (r"\bukiyo-?e\b", ["ukiyo-e", "traditional_media"]),
    (r"\bnihonga\b", ["nihonga", "traditional_media"]),
    (r"\blithograph\b|\betching\b|\bengraving\b", ["lithograph", "traditional_media"]),
    (r"\brisograph\b|\briso\b", ["risograph"]),
    (r"\bscreen ?print\b|\bsilkscreen\b|\bstencil\b", ["stencil"]),
    (r"\bcollage\b|\bphotomontage\b", ["collage"]),
    (r"\bpixel\b|\b8-?bit\b|\b16-?bit\b", ["pixel_art"]),
    (r"\bvoxel\b", ["pixel_art", "3d"]),
    (r"\blow[- ]poly\b", ["low_poly", "3d"]),
    (r"\bwireframe\b", ["wireframe", "3d"]),
    (r"\b3d\b|\brender\b|\bcgi\b|\boctane\b|\bunreal\b|\bblender\b|\bredshift\b|\bv-?ray\b", ["3d"]),
    (r"\bclay\b|\bclaymation\b|\bstop[- ]motion\b", ["claymation", "stop_motion"]),
    (r"\bphotograph|\bphoto\b|\bcamera\b|\bfilm stock\b|\bdslr\b", ["photo_(medium)"]),
    (r"\bphotoreal", ["photorealistic", "realistic"]),
    (r"(?<!paper )(?<!wood )(?<!canvas )(?<!board )\bgrain\b", ["film_grain"]),
    (r"\bmonochrome\b|\bblack[- ]and[- ]white\b|\bb&w\b|\bsilver[- ]gelatin\b", ["monochrome", "greyscale"]),
    (r"\bsepia\b|\bdaguerreotype\b|\btintype\b|\bcollodion\b|\balbumen\b", ["sepia"]),
    (r"\bcyanotype\b|\bprussian blue\b", ["blue_theme", "monochrome"]),
    (r"\bpolaroid\b|\binstant film\b", ["instant_photo"]),
    (r"\bnoir\b|\bchiaroscuro\b", ["chiaroscuro", "high_contrast"]),
    (r"\bneon\b", ["neon_palette", "glowing"]),
    (r"\bvaporwave\b", ["vaporwave"]),
    (r"\bglitch\b|\bvhs\b|\bcrt\b|\bscanline", ["glitch"]),
    (r"\bhologram", ["holographic", "glowing"]),
    (r"\bstained glass\b", ["stained_glass"]),
    (r"\bgold ground\b|\bgold leaf\b|\bgilded\b", ["gold"]),
    (r"\bmarble\b", ["marble"]),
    (r"\bmetal\b|\bchrome\b", ["metallic"]),
    (r"\bplastic\b|\btoy\b|\bvinyl\b", ["plastic"]),
    (r"\bknit\b|\bcrochet\b|\bfelt", ["knitted", "textured"]),
    (r"\bembroider", ["embroidery", "textured"]),
    (r"\bpaper ?craft\b|\borigami\b|\bcut[- ]paper\b", ["papercraft"]),
    (r"\bblueprint\b|\bschematic\b|\bdiagram\b|\btechnical drawing\b", ["diagram"]),
    (r"\bposter\b", ["poster"]),
    (r"\bcomic\b", ["comic"]),
    (r"\bstoryboard\b", ["storyboard"]),
    (r"\bcharacter sheet\b|\bmodel sheet\b", ["character_sheet", "reference_sheet"]),
    (r"\bturnaround\b", ["turnaround", "multiple_views"]),
    (r"\bcontact sheet\b", ["contact_sheet", "multiple_views"]),
    (r"\bmagazine cover\b", ["magazine_cover"]),
    (r"\balbum cover\b", ["album_cover"]),
    (r"\bmap\b|\bcartograph", ["map"]),
    (r"\bwallpaper\b", ["wallpaper"]),
    (r"\bicon\b", ["icon_(computing)"]),
    (r"\btrading card\b|\btarot\b", ["trading_card"]),
    (r"\bwidescreen\b|\b2\.39\b|\bletterbox", ["widescreen"]),
    (r"\bminimal", ["minimalism"]),
    (r"\bart deco\b", ["art_deco"]),
    (r"\bart nouveau\b", ["art_nouveau"]),
    (r"\bcubis", ["cubism"]),
    (r"\bimpressionis", ["impressionism"]),
    (r"\bsurreal", ["surreal"]),
    (r"\bpsychedelic\b", ["psychedelic"]),
    (r"\bpastel colou?rs?\b|\bpastel palette\b", ["pastel_colors"]),
    (r"\bmuted\b|\bdesaturat", ["muted_color"]),
    (r"\blimited palette\b|\bfew colou?rs\b", ["limited_palette"]),
    (r"\bhigh[- ]contrast\b", ["high_contrast"]),
    (r"\bbokeh\b|\bshallow depth\b", ["depth_of_field", "bokeh"]),
    (r"\bmotion blur\b|\bpanning\b", ["motion_blur"]),
    (r"\blong exposure\b", ["long_exposure"]),
    (r"\bbacklit\b|\bbacklight|\brim light", ["backlighting", "rim_lighting"]),
    (r"\bsilhouette\b", ["silhouette"]),
    (r"\bunderwater\b", ["underwater"]),
    (r"\blens flare\b|\bhalation\b|\banamorphic\b", ["lens_flare"]),
    (r"\bvignett", ["vignetting"]),
    (r"\bcinematic\b|\bfilmic\b", ["cinematic_lighting"]),
    (r"\bscenery\b|\blandscape\b|\bbackground art\b|\bmatte painting\b", ["scenery"]),
    (r"\bseamless\b|\bstudio backdrop\b|\bwhite background\b", ["simple_background"]),
    (r"\bline ?art\b|\bclean line\b", ["lineart"]),
    (r"\bno outlines?\b|\bwithout outlines\b", ["no_lineart"]),
    (r"\bthick outline|\bheavy outline|\bbold outline", ["outline"]),
    (r"\bflat colou?r\b|\bflat fill\b|\bflat shading\b", ["flat_color"]),
    (r"\bgradient\b", ["gradient"]),
    (r"\bglow", ["glowing"]),
    (r"\bwet\b|\brain\b", ["wet"]),
    (r"\brust", ["rust", "textured"]),
    (r"\bwood grain\b|\bwooden\b", ["wood"]),
    (r"\bsketch\b|\bunfinished\b|\brough\b", ["sketch"]),
    (r"\bconcept art\b", ["concept_art"]),
    (r"\bgame cg\b|\bvisual novel\b", ["game_cg"]),
    # --- second pass: terms the first pass missed in the shipped catalog ----
    (r"\bmezzotint\b|\bchromolithograph\b|\bletterpress\b|\bintaglio\b", ["lithograph", "traditional_media"]),
    (r"\bfresco\b|\bmural\b|\bwall painting\b|\bshan shui\b|\bgongbi\b", ["painting_(medium)", "traditional_media"]),
    (r"\bfauvis|\bexpressionis|\bart brut\b|\boutsider art\b", ["painting_(medium)"]),
    (r"\bcolou?r field\b|\bstained canvas\b", ["gradient", "painting_(medium)"]),
    (r"\bdot painting\b|\bpointillis", ["halftone", "traditional_media"]),
    (r"\bgraffiti\b|\bwildstyle\b|\bspray paint\b|\bstencil art\b", ["stencil"]),
    (r"\barabesque\b|\billumination\b|\bmanuscript\b", ["gold", "traditional_media"]),
    (r"\begyptian\b|\bhieroglyph", ["traditional_media", "flat_color"]),
    (r"\bcutout\b|\bpaper cut", ["papercraft"]),
    (r"\bvector\b|\bflash animation\b", ["flat_color", "outline"]),
    (r"\bgolden age\b|\brubber hose\b|\bslapstick\b|\bsunday (?:fun-?page|funnies)\b", ["retro_artstyle", "flat_color"]),
    (r"\bnewsprint\b|\bnewspaper\b|\bcomic strip\b", ["comic", "halftone"]),
    (r"\bairbrush\b", ["airbrush_(medium)"]),
    (r"\bdither", ["dithering", "pixel_art"]),
    (r"\bmosaic\b|\btesser", ["mosaic"]),
    (r"\bembroider|\bcross[- ]stitch\b|\btapestry\b", ["embroidery", "textured"]),
    (r"\bneon sign\b|\blightbox\b|\bled\b", ["glowing", "neon_palette"]),
    (r"\bsilhouette theat|\bshadow puppet\b", ["silhouette"]),
    (r"\bstained\b", ["stained_glass"]),
    (r"\bposterized?\b|\bposterisation\b", ["flat_color", "high_contrast"]),
    (r"\bduotone\b|\btwo[- ]colou?r\b", ["duotone", "limited_palette"]),
    (r"\bsepia\b|\baged paper\b|\byellowed\b", ["sepia"]),
    (r"\bcaricature\b|\bcartoon\b", ["flat_color", "outline"]),
    (r"\bstorybook\b|\bpicture book\b|\bchildren'?s book\b", ["watercolor_(medium)", "traditional_media"]),
    (r"\bfashion\b|\beditorial\b|\bcatalog\b|\bcampaign\b", ["photo_(medium)"]),
    (r"\bportrait\b", ["portrait"]),
    (r"\bstill life\b", ["still_life"]),
    # --- drawing / study terms -------------------------------------------
    (r"\bgraphite\b|\bpencil\b|\bacademic (?:tone|study)\b|\blife study\b", ["graphite_(medium)", "sketch", "monochrome", "traditional_media"]),
    (r"\bconte\b|\bsanguine\b|\bsilverpoint\b", ["traditional_media", "monochrome", "sketch"]),
    (r"\bhatch|\btonal build|\bshading study\b", ["cross-hatching", "hatching_(texture)"]),
    (r"\bpaper grain\b|\bcartridge paper\b|\btoothy paper\b", ["textured", "traditional_media"]),
    (r"\bcharcoal\b|\bvelvet black\b", ["charcoal_(medium)", "monochrome", "traditional_media"]),
    (r"\bgesture\b|\bloose study\b|\bquick study\b", ["sketch", "unfinished"]),
    (r"\bportrait study\b|\bhead study\b", ["portrait", "sketch"]),
]

COMPILED = [(re.compile(pattern, re.I), tags) for pattern, tags in RULES]


def normalise_tags(raw_tags):
    """Clean a raw tag list: lowercase, alias-map, vocabulary-filter, dedupe.

    Returns ``(tags, dropped)``.
    """
    out = []
    dropped = []
    seen = set()
    for raw in raw_tags or []:
        tag = str(raw).strip().lower().replace(" ", "_")
        tag = tag.strip(",;.")
        if not tag:
            continue
        tag = ALIASES.get(tag, tag)
        if tag not in VOCAB:
            dropped.append(raw)
            continue
        if tag in seen:
            continue
        seen.add(tag)
        out.append(tag)
    return out, dropped


def tags_for_text(*chunks, limit=8):
    """Derive booru tags from free text (entry name + natural-language clause)."""
    text = " ".join(str(chunk or "") for chunk in chunks)
    out = []
    seen = set()
    for pattern, tags in COMPILED:
        if not pattern.search(text):
            continue
        for tag in tags:
            if tag in seen or tag not in VOCAB:
                continue
            seen.add(tag)
            out.append(tag)
    return out[:limit]


NEGATIVE_TAG_MAP = {
    "photo": "photo_(medium)",
    "photograph": "photo_(medium)",
    "photoreal": "photorealistic",
    "photorealistic": "photorealistic",
    "photoreal photograph": "photorealistic",
    "3d": "3d",
    "3d render": "3d",
    "3d cgi": "3d",
    "cgi": "3d",
    "plastic 3d": "3d",
    "plastic game cgi": "3d",
    "anime": "anime_coloring",
    "anime cel": "cel_shading",
    "cel shading": "cel_shading",
    "cartoon": "anime_coloring",
    "cartoon outlines": "outline",
    "illustration": "painting_(medium)",
    "drawing": "sketch",
    "sketch": "sketch",
    "painting": "painting_(medium)",
    "oil painting": "oil_painting_(medium)",
    "watercolor": "watercolor_(medium)",
    "watercolour": "watercolor_(medium)",
    "watercolor illustration": "watercolor_(medium)",
    "watercolor wash": "watercolor_(medium)",
    "graphite sketch": "graphite_(medium)",
    "comic ink": "comic",
    "pixel art": "pixel_art",
    "monochrome": "monochrome",
    "greyscale": "greyscale",
    "grayscale": "greyscale",
    "live action": "photo_(medium)",
    "raw dslr photograph": "photo_(medium)",
    "color snapshot": "photo_(medium)",
}


def negative_tags_for(text, limit=6):
    """Map a comma-separated natural-language negative into booru tags."""
    out = []
    seen = set()
    for chunk in str(text or "").split(","):
        key = re.sub(r"\s+", " ", chunk.strip().lower())
        if not key:
            continue
        tag = NEGATIVE_TAG_MAP.get(key)
        if not tag:
            for phrase, mapped in NEGATIVE_TAG_MAP.items():
                if phrase in key:
                    tag = mapped
                    break
        if not tag or tag in seen or tag not in VOCAB:
            continue
        seen.add(tag)
        out.append(tag)
    return out[:limit]
